version: '3.8'

services:
  pawsql-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: pawsql/pawsql-mcp-server:latest
    container_name: pawsql-mcp-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1g
      # Configure these values for your deployment
      - PAWSQL_ADMIN_USERS=admin@example.com
      - PAWSQL_READONLY_USERS=readonly@example.com
      - PAWSQL_SESSION_TIMEOUT_HOURS=24
      - PAWSQL_SESSION_CLEANUP_INTERVAL_MINUTES=60
      - PAWSQL_SESSION_MAX_PER_USER=5
      # Optional default API credentials (for fallback)
      #- PAWSQL_API_BASE_URL=https://www.pawsql.com
      #- PAWSQL_EDITION=cloud
      #- PAWSQL_API_EMAIL=default@example.com
      #- PAWSQL_API_PASSWORD=defaultpassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
