spring:
  application:
    name: pawsql-mcp-server
  main:
    web-application-type: servlet
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: pawsql-optimizer
        version: 0.0.1
        protocol: STATELESS
        type: sync
        capabilities:
          completion: true
          prompt: true
          resource: true
          tool: true
        streamable-http:
          mcp-endpoint: /mcp

server:
  port: ${PAWSQL_MCP_PORT:8766}

logging:
  level:
    io.modelcontextprotocol: WARN
    org.springframework.ai.mcp: WARN

jwt:
  secret: ${PAWSQL_MCP_TOKEN_SECRET:gmYTZlXESyoSTicizrZoIsLi8GPRL0QHdykpDarCUtCmvbT4o7d4mLrTcV16wflprC1QfIoQF42uLFL6aVsIjQ==}
  expiration: 86400000000

pawsql:
  anonymous:
    user-key: ${PAWSQL_ANONYMOUS_USER_KEY:23927924-010A7F59-69ABCF01-B1E1D303}
